version: '3'

services:
  app:
    container_name: app
    image: netcoreapp
    build:
      context: .
    ports:
      - "20000:80"
    networks:
      - internal
    depends_on:
      - "db"

  db:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest    
    ports:
      - "1433:1433"   
    environment:
      SA_PASSWORD: "Pass123*"
      ACCEPT_EULA: "Y"       
    networks:
      - internal

networks: 
    internal:
        driver: bridge
